app:
  db:
    name: ${OP_DB:order-planning-db}
    user: ${OP_USER:sa}
    password: ${OP_PASSWORD:}

spring:
  #
  # DATASOURCE CONFIG
  #
  datasource:
    url: jdbc:h2:mem:${app.db.name};DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: ${app.db.user}
    password: ${app.db.password}

  #
  # FLYWAY CONFIG
  #
  flyway:
    enabled: true

  #
  # HIBERNATE CONFIG
  #
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none